[package]
name = "openbabel"
version = "0.3.4"
edition = "2018"
authors = ["Qin Wan <rogerwq@gmail.com>"]
license = "MIT"
description = "Rust bindings to cheminformatics toolbox OpenBabel"
repository = "https://github.com/rogerwq/openbabel-rust"
homepage = "https://github.com/rogerwq/openbabel-rust"
documentation = "https://docs.rs/openbabel"
keywords = ["cheminformatics", "openbabel"]
categories = ["science"]

[dependencies]
cxx = "1.0"
ob_rs = { package = "openbabel-sys", version = "0.1.8" }
chiral-db-fp-kind = "0.1.0"

[dev-dependencies]
criterion = "0.3.5"
chiral_db_sources = { package = "chiral-db-sources", version = "0.2.0" }

[[bench]]
name = "fingerprint"
harness = false

[[bench]]
name = "substructure"
harness = false

[[example]]
name = "fingerprint"
path = "examples/fingerprint.rs"